language: python
python:
  - "2.7"
  - "3.3"
install: git clone https://github.com/hayaku/tests.git test
script: make -f ./test/makefile.travis test
branches:
  only:
    - travis
notifications:
  email: false
